# -*- coding: utf-8 -*-
"""tumulus_yolo_pipeline_short.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18F2TQQAbWG4ge6UaABcu3MbLxRUWGuTq
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

import zipfile, os, glob

# Delete the Google Docs converted files first
import shutil
shutil.rmtree('/content/drive/MyDrive/ml-training/dataset/train/labels/')
shutil.rmtree('/content/drive/MyDrive/ml-training/dataset/val/labels/')
os.makedirs('/content/drive/MyDrive/ml-training/dataset/train/labels/')
os.makedirs('/content/drive/MyDrive/ml-training/dataset/val/labels/')

# Unzip
with zipfile.ZipFile('/content/drive/MyDrive/ml-training/dataset/labels_train.zip', 'r') as z:
    z.extractall('/tmp/labels_train/')

with zipfile.ZipFile('/content/drive/MyDrive/ml-training/dataset/labels_val.zip', 'r') as z:
    z.extractall('/tmp/labels_val/')

# Copy only .txt files
import shutil, glob
for f in glob.glob('/tmp/labels_train/**/*.txt', recursive=True):
    shutil.copy(f, '/content/drive/MyDrive/ml-training/dataset/train/labels/')
for f in glob.glob('/tmp/labels_val/**/*.txt', recursive=True):
    shutil.copy(f, '/content/drive/MyDrive/ml-training/dataset/val/labels/')

# Verify
all_labels = glob.glob('/content/drive/MyDrive/ml-training/dataset/train/labels/*.txt')
non_empty = [f for f in all_labels if os.path.getsize(f) > 0]
print(f"Total: {len(all_labels)}, Non-empty: {len(non_empty)}")

import torch
print(torch.cuda.is_available())  # must be True
!nvidia-smi

import yaml

yaml_path = '/content/drive/MyDrive/ml-training/dataset/dataset.yaml'

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

print("Current content:", data)  # show what's in there now

data['path'] = '/content/drive/MyDrive/ml-training/dataset'
data['train'] = 'train/images'
data['val'] = 'val/images'

with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

print("Updated:", data)

from ultralytics import YOLO

model = YOLO('yolov8s.pt')
model.train(
    data=yaml_path,
    epochs=200,
    batch=16,      # increase from 8 since T4 has 16GB VRAM
    imgsz=640,
    project='/content/drive/MyDrive/ml-training/tumulus_runs',
    name='train_colab'
)

